In [ ]:
# vektor python numpy with range value
import numpy as np
print("vektor default python\n")
a = np.arange(1,20,1)
b = np.arange(1,20,2)
import numpy as np
print (" \n vektor via numpy \n")

# vektor via numpy
c = np.array ([1,2,3,4,5])
d = np.array ([1.5, 2.5, 5, 6, 7])
print("Nilai a :")
print(a)
print("Nilai b :")
print(b)
print("======")
print(a.ndim)
print("======")
print(a.shape)

# mengubah dari 1D menjadi matrik 2D
a = np.arange(1,21,1)
c = a.reshape((4,5))
print("======")
print(c)

list1 = ["apple", "banana", "cherry"]
list2 = [1, 5, 7, 9, 3]
list3 = [True, False, False]
list4 = ["abc", 34, True, 40, "male"]
print("======")
print(list1); 

#data frame
import pandas as pd
df = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
 columns=['a', 'b', 'c'])
print("======")
print(df)

# Membaca data dari file dengan format CSV
import pandas as pd
data = pd.read_csv("Data.csv", sep=";")
print("======")
print(data)

print("======")
# Membaca data dari file dengan format text (delimeter)
print("\n read text data with tab delimiter")
with open ('Data.txt') as data:
    print(data.read())

print("======")
# Membaca data dari URL
import pandas as pd
f = pd.read_csv('http://www.exploredata.net/ftp/Spellman.csv')
print(f)


import numpy as sp
traffic = sp.genfromtxt("web_traffic.tsv",delimiter='\t')
print(traffic[:10])
print(traffic.shape)
x = traffic[:,0]
y = traffic[:,1]
x = x[~sp.isnan(y)]
y = y[~sp.isnan(y)]
import matplotlib.pyplot as plt
plt.scatter(x,y)
plt.title("Web traffic last month")
plt.xlabel("Time")
plt.ylabel("Hits/hour")
plt.xticks([w*7*24 for w in range(10)],['week %i' %w for w in
range(10)])
plt.autoscale(tight=True)
plt.grid()

# pilihan load image (contoh logo ipb)
import matplotlib.pyplot as plt
import cv2
import numpy as np
print("read images using opencv")
five = cv2.imread("5.png")
print("======")
print(five.shape)
print("======")
print(five.size)
print("======")
plt.imshow(five)
cv2.waitKey(0)

# acces pixel of images per postion
pixels = five[100,100]
print(pixels)

vektor default python

 
 vektor via numpy 

Nilai a :
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Nilai b :
[ 1  3  5  7  9 11 13 15 17 19]
1
(19,)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
['apple', 'banana', 'cherry']
   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9
   Nama Pasien  Umur Gender Diagnosa Sakit
0         Anto    24      L          Tidak
1         Budi    35      L             Ya
2          Adi    55      L             Ya
3       Delima    32      P             Ya
4         Dodi    21      L          Tidak
5      Tukiyem    19      P          Tidak
6         Rama    23      L          Tidak
7        Santi    35      P          Tidak
8         Mery    44      P             Ya
9        Yanti    27      P          Tidak
10       Parto    43      L             Ya
11         Dea    24      P          Tidak

 read text data with tab delimiter
NamaPasien	Umur	Gender	Diagnosa Sakit
Anto		24	L	Tidak
Budi		35	L	Ya
Adi		55	L	Ya
Delima		32	P